In [1]:
# import numpy, matplotlib, and pandas libraries

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# import the dataset

dataset = pd.read_csv('Data.csv')

In [12]:
# select the independent and dependent variables

# the first 3 columns are the independent variables. select all their values
x = dataset.iloc[:,:-1].values
# the last column is the dependent variable. select it's value
y = dataset.iloc[:,-1].values

In [15]:
# take care of missing data

# replace the missing value with the average of the column that data belongs to
# import SimpleImputer
from sklearn.impute import SimpleImputer
# use imputer to replace the NaN values with mean
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
# use imputer.fit to replace all the NaN values wiith mean. fit function select the numerical values
imputer.fit(x[:, 1:3])
# transform method replaces the missing values with mean
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [21]:
# now that the missing values have been replaced with the mean, we will now take care of categorical values

# the dataset has country column with categories. we will encode them into numbers.

# encode the independent variable
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
# give the parameters for transforming the country column
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])],remainder='passthrough')
# transform the x
x = np.array(ct.fit_transform(x))

# encode the dependent variable
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit_transform(y)

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [27]:
# split the dataset into training and test set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

[[1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 35.0 58000.0]]
